"""Share link generation for Vellum Brief sheets.

The token is phone-bound — only valid for the recipient's number — per
the auth module (``vellum.auth.tokens``).
"""

from __future__ import annotations

from urllib.parse import quote, urlencode


def generate_share_url(
    base_url: str,
    sheet_id: str,
    token: str,
) -> str:
    """Build a share URL for a Brief sheet.

    Parameters
    ----------
    base_url:
        API root, e.g. ``https://api.amplifiedpartners.ai``.
    sheet_id:
        The sheet's UUID.
    token:
        Phone-bound JWT (or opaque token) generated by the auth module.

    Returns
    -------
    str
        Full URL like
        ``https://api.amplifiedpartners.ai/vellum/brief/{sheet_id}?token={token}``
    """
    # Strip trailing slash from base_url for consistent formatting
    base = base_url.rstrip("/")
    path = f"/vellum/brief/{quote(sheet_id, safe='')}"
    query = urlencode({"token": token})
    return f"{base}{path}?{query}"
