"""test_workflow_is_deterministic — invariant §6.6.

No LLM calls in workflow bodies. Workflows are deterministic.
LLM calls happen only in tagged activities.

Dana | 2026-05-20 | From Computer's Loom spec §6
"""

from __future__ import annotations

import ast
import importlib
import inspect

import pytest

# All workflow modules
WORKFLOW_MODULES = [
    "loom.workflows.brain_health",
    "loom.workflows.agent_watcher",
    "loom.workflows.budget_guard",
    "loom.workflows.kaizen_generator",
    "loom.workflows.loop_closer",
]

# Known LLM-related imports that would indicate non-determinism
LLM_INDICATORS = [
    "litellm",
    "openai",
    "anthropic",
    "langchain",
    "llm",
    "chat_completion",
    "ChatCompletion",
    "completion",
]


class TestWorkflowDeterminism:
    """Workflow bodies must be deterministic — no LLM calls."""

    def test_no_llm_imports_in_workflows(self) -> None:
        """Workflow modules must not import LLM libraries."""
        for module_name in WORKFLOW_MODULES:
            module = importlib.import_module(module_name)
            source = inspect.getsource(module)

            for indicator in LLM_INDICATORS:
                # Check import lines specifically
                import_lines = [
                    line.strip() for line in source.splitlines()
                    if line.strip().startswith(("import ", "from "))
                ]
                for line in import_lines:
                    assert indicator not in line, (
                        f"Workflow {module_name} imports LLM library: {line}"
                    )

    def test_kaizen_rule_book_is_static(self) -> None:
        """The rule book is a static dict, not generated by LLM."""
        from loom.workflows.kaizen_generator import RULE_BOOK

        assert isinstance(RULE_BOOK, dict)
        # Every rule must have required fields
        for kind, rule in RULE_BOOK.items():
            assert "title" in rule, f"Rule {kind} missing title"
            assert "rationale" in rule, f"Rule {kind} missing rationale"
            assert "intervention" in rule, f"Rule {kind} missing intervention"

    def test_propose_for_finding_is_deterministic(self) -> None:
        """Same input → same output, every time."""
        from loom.findings import Finding
        from loom.workflows.kaizen_generator import propose_for_finding

        f = Finding(
            id="fixed-id",
            kind="triangulation_drop",
            source_workflow="test",
            evidence={"rate": 0.5},
        )

        p1 = propose_for_finding(f)
        p2 = propose_for_finding(f)

        assert p1 is not None
        assert p2 is not None
        assert p1.title == p2.title
        assert p1.rationale == p2.rationale
        assert p1.intervention == p2.intervention

    def test_evaluate_proposal_is_deterministic(self) -> None:
        """Evaluation logic is pure comparison, no LLM."""
        from loom.proposals import Proposal
        from loom.workflows.loop_closer import evaluate_proposal

        p = Proposal(
            title="Test",
            intervention={"action": "test"},
            baseline_metric={"total": 100},
        )

        r1 = evaluate_proposal(p, {"total": 100}, {"total": 120})
        r2 = evaluate_proposal(p, {"total": 100}, {"total": 120})

        assert r1["confirmed"] == r2["confirmed"]
        assert r1["reason"] == r2["reason"]

    def test_no_random_in_workflow_logic(self) -> None:
        """Workflow logic should not use random for decisions."""
        for module_name in WORKFLOW_MODULES:
            module = importlib.import_module(module_name)
            source = inspect.getsource(module)

            import_lines = [
                line.strip() for line in source.splitlines()
                if line.strip().startswith(("import ", "from "))
            ]
            for line in import_lines:
                assert "random" not in line, (
                    f"Workflow {module_name} imports random: {line}"
                )
